//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningProject.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockExitDetail
    {
        public long id { get; set; }
        public long stockExitId { get; set; }
        public long foodItemId { get; set; }
        public decimal quantity { get; set; }
        public string observation { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<long> stockEntryDetailId { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual StockEntryDetail StockEntryDetail { get; set; }
        public virtual StockExit StockExit { get; set; }
    }
}
