//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningProject.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockEntryDetail()
        {
            this.StockExitDetails = new HashSet<StockExitDetail>();
        }
    
        public long id { get; set; }
        public long stockEntryId { get; set; }
        public long foodItemId { get; set; }
        public decimal quantity { get; set; }
        public decimal unitPrice { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<decimal> currentQuantity { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual StockEntry StockEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockExitDetail> StockExitDetails { get; set; }
    }
}
